### ISSUE TITLE
no refresh of counters data

### ISSUE THREAD

**Issue by keiser1080** [blanosko/gas-meter-ha#1]
Hi,

Do we need to pool (cron script or other) counters data to be updated ? 
i am using ebusd+homeassistant+mosquitto under individual docker container.
i am still busy collecting data on the step "Taking The Readings" 
The PrEnergySumHc1 PrEnergySumHwc1 seems to not update.
To be able to read i have two options:

1. using nc 
```
FIELD_HC=`echo "r -f -c $circuit PrEnergySumHc1" |nc -q 1 127.0.0.1 $port| head -n 1`
FIELD_HWC=`echo "r -f -c $circuit PrEnergySumHwc1" |nc -q 1 127.0.0.1 $port| head -n 1`
```
2. publishing on 
```
ebusd/bai/PrEnergySumHwc1/get
ebusd/bai/PrEnergySumHc1/get
```
my ebusdconfig:
```
EBUSD_POLLINTERVAL: 180 # don't know if it's needed
EBUSD_MQTTINT: "/etc/ebusd/mqtt-hassio.cfg" # i use the default one without any change
EBUSD_MQTTVERBOSE: "" # don't know if it's needed
EBUSD_MQTTCHANGES: ""  # don't know if it's needed
```

**Comment by blanosko** [comment]
I'll help you with this. Have you reset the counters? They might be full, and in that case, they won't increase anymore.

Please provide the output of the following commands from your ebusd container:
```
ebusctl r PrEnergySumHc1
ebusctl r PrEnergySumHwc1
ebusctl r PrEnergyCountHc1
ebusctl r PrEnergyCountHwc1
```

Below is my ebusd configuration file:
```
EBUSD_OPTS="--scanconfig -d enh:<REDACTED>:9999 -l /var/log/ebusd.log --configpath=/root/ebusd-configuration/ebusd/2.1.x/en  --mqtthost=<REDACTED> --mqttport=1883 --mqttuser=ebusd --mqttpass=<REDACTED> --mqttjson --accesslevel=\"*\" --pollinterval=10"
```

As you can see, I am using custom ebusd-configuration files where I can specify what is polled and what is not. To ensure that PrEnergySumHc1 and Hwc1 are polled when the value on the bus changes, I have modified the following lines in my loaded configuration:
```
r1;w,,PrEnergySumHwc1,PrEnergySumDHW1_DK,,,,"C500",,,ULG,,,Predictive Maintenance data
r1;w,,PrEnergyCountHwc1,PrEnergyCountDHW1_DK,,,,"C600",,,ULG,,,Predictive Maintenance data
r1;w,,PrEnergySumHc1,PrEnergySumCH1_DK,,,,"F500",,,ULG,,,Predictive Maintenance data
r1;w,,PrEnergyCountHc1,PrEnergyCountCH1_DK,,,,"F600",,,ULG,,,Predictive Maintenance data
```
You can refer to the ebusd wiki for more details [https://github.com/john30/ebusd/wiki/4.1.-Message-definition](https://github.com/john30/ebusd/wiki/4.1.-Message-definition).

If you are using default configuration files, you can either adopt my configuration or periodically send a /get payload to the specific MQTT topics you need to poll. (Note: The value is sent to MQTT only if it has changed.)

Since I don't use mqtt-hassio.cfg (autopopulating entities), I manually configure all MQTT sensors in configuration.yaml.

**Comment by keiser1080** [comment]
> I'll help you with this. Have you reset the counters? They might be full, and in that case, they won't increase anymore.
> 
> Please provide the output of the following commands from your ebusd container:
> 
> ```
> ebusctl r PrEnergySumHc1
> ebusctl r PrEnergySumHwc1
> ebusctl r PrEnergyCountHc1
> ebusctl r PrEnergyCountHwc1
> ```
> 
> Below is my ebusd configuration file:
> 
> ```
> EBUSD_OPTS="--scanconfig -d enh:<REDACTED>:9999 -l /var/log/ebusd.log --configpath=/root/ebusd-configuration/ebusd/2.1.x/en  --mqtthost=<REDACTED> --mqttport=1883 --mqttuser=ebusd --mqttpass=<REDACTED> --mqttjson --accesslevel=\"*\" --pollinterval=10"
> ```
> 
> As you can see, I am using custom ebusd-configuration files where I can specify what is polled and what is not. To ensure that PrEnergySumHc1 and Hwc1 are polled when the value on the bus changes, I have modified the following lines in my loaded configuration:
> 
> ```
> r1;w,,PrEnergySumHwc1,PrEnergySumDHW1_DK,,,,"C500",,,ULG,,,Predictive Maintenance data
> r1;w,,PrEnergyCountHwc1,PrEnergyCountDHW1_DK,,,,"C600",,,ULG,,,Predictive Maintenance data
> r1;w,,PrEnergySumHc1,PrEnergySumCH1_DK,,,,"F500",,,ULG,,,Predictive Maintenance data
> r1;w,,PrEnergyCountHc1,PrEnergyCountCH1_DK,,,,"F600",,,ULG,,,Predictive Maintenance data
> ```
> 
> You can refer to the ebusd wiki for more details https://github.com/john30/ebusd/wiki/4.1.-Message-definition.
> 
> If you are using default configuration files, you can either adopt my configuration or periodically send a /get payload to the specific MQTT topics you need to poll. (Note: The value is sent to MQTT only if it has changed.)
> 
> Since I don't use mqtt-hassio.cfg (autopopulating entities), I manually configure all MQTT sensors in configuration.yaml.

Thanks for your answer.
I am using pretty the same config.
I will add the R1 and change the pull interval.


update: thanks it's working now

**Comment by Pelikanoooo** [comment]
hello, my counters are stuck on the same value all the time, could someone tell me as a complete amateur how to fix it?
